version: "3"
services:
  # 其他配置参考 https://hub.docker.com/r/tiangolo/uvicorn-gunicorn-fastapi/

  star-eater:
    build: .
    container_name: star-eater
    ports:
      - "10492:80" # 映射端口到宿主机 宿主机端口:容器端口
    env_file:
      - ".env.prod" # fastapi 使用的环境变量文件
    environment:
      - ENVIRONMENT=prod # 配置 nonebot 运行环境，此项会被 .env 文件覆盖
    network_mode: bridge
    volumes:
      - star-eater-volume:/app/data/
volumes:
  star-eater-volume:
    external: false
